version: "3"
services:
  mc:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.21.11"
      ONLINE_MODE: "FALSE"
    volumes:
      - ./server-data:/data
      - ./target/vanishpp-1.2.0.jar:/data/plugins/Vanishpp.jar
